name: Deploy to Render - Tests Passed

on:
  workflow_run:
    workflows:
      - Pytest
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04

    steps:
      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"
